language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - python setup.py install
script:
  py.test tests --cov named_dates --cov-report term-missing

after_success:
  coveralls
