language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - python setup.py install
script:
  py.test --cov named_dates .
after_success:
  coveralls
