language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - python setup.py install
script:
  py.test --cov named_dates --cov-report html .
after_success:
  coveralls
