language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
script:
  coverage run --source=named_dates setup.py test
after_success:
  coveralls
